# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/kerfur/Downloads/clion/clion-2019.2/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/kerfur/Downloads/clion/clion-2019.2/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kerfur/DEV/MY_GITHUB/Midnight-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kerfur/DEV/MY_GITHUB/Midnight-Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/kerfur/Downloads/clion/clion-2019.2/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/kerfur/Downloads/clion/clion-2019.2/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/kerfur/Downloads/clion/clion-2019.2/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/kerfur/Downloads/clion/clion-2019.2/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/kerfur/Downloads/clion/clion-2019.2/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/kerfur/Downloads/clion/clion-2019.2/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/kerfur/Downloads/clion/clion-2019.2/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/kerfur/Downloads/clion/clion-2019.2/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kerfur/DEV/MY_GITHUB/Midnight-Engine/CMakeFiles /home/kerfur/DEV/MY_GITHUB/Midnight-Engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kerfur/DEV/MY_GITHUB/Midnight-Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MidnightEngine

# Build rule for target.
MidnightEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MidnightEngine
.PHONY : MidnightEngine

# fast build rule for target.
MidnightEngine/fast:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/build
.PHONY : MidnightEngine/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f external/glfw/CMakeFiles/uninstall.dir/build.make external/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f external/glfw/src/CMakeFiles/glfw.dir/build.make external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) -f external/glfw/src/CMakeFiles/update_mappings.dir/build.make external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named wave

# Build rule for target.
wave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wave
.PHONY : wave

# fast build rule for target.
wave/fast:
	$(MAKE) -f external/glfw/examples/CMakeFiles/wave.dir/build.make external/glfw/examples/CMakeFiles/wave.dir/build
.PHONY : wave/fast

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) -f external/glfw/examples/CMakeFiles/simple.dir/build.make external/glfw/examples/CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named gears

# Build rule for target.
gears: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gears
.PHONY : gears

# fast build rule for target.
gears/fast:
	$(MAKE) -f external/glfw/examples/CMakeFiles/gears.dir/build.make external/glfw/examples/CMakeFiles/gears.dir/build
.PHONY : gears/fast

#=============================================================================
# Target rules for targets named boing

# Build rule for target.
boing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boing
.PHONY : boing

# fast build rule for target.
boing/fast:
	$(MAKE) -f external/glfw/examples/CMakeFiles/boing.dir/build.make external/glfw/examples/CMakeFiles/boing.dir/build
.PHONY : boing/fast

#=============================================================================
# Target rules for targets named heightmap

# Build rule for target.
heightmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heightmap
.PHONY : heightmap

# fast build rule for target.
heightmap/fast:
	$(MAKE) -f external/glfw/examples/CMakeFiles/heightmap.dir/build.make external/glfw/examples/CMakeFiles/heightmap.dir/build
.PHONY : heightmap/fast

#=============================================================================
# Target rules for targets named splitview

# Build rule for target.
splitview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 splitview
.PHONY : splitview

# fast build rule for target.
splitview/fast:
	$(MAKE) -f external/glfw/examples/CMakeFiles/splitview.dir/build.make external/glfw/examples/CMakeFiles/splitview.dir/build
.PHONY : splitview/fast

#=============================================================================
# Target rules for targets named offscreen

# Build rule for target.
offscreen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 offscreen
.PHONY : offscreen

# fast build rule for target.
offscreen/fast:
	$(MAKE) -f external/glfw/examples/CMakeFiles/offscreen.dir/build.make external/glfw/examples/CMakeFiles/offscreen.dir/build
.PHONY : offscreen/fast

#=============================================================================
# Target rules for targets named particles

# Build rule for target.
particles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particles
.PHONY : particles

# fast build rule for target.
particles/fast:
	$(MAKE) -f external/glfw/examples/CMakeFiles/particles.dir/build.make external/glfw/examples/CMakeFiles/particles.dir/build
.PHONY : particles/fast

#=============================================================================
# Target rules for targets named sharing

# Build rule for target.
sharing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sharing
.PHONY : sharing

# fast build rule for target.
sharing/fast:
	$(MAKE) -f external/glfw/examples/CMakeFiles/sharing.dir/build.make external/glfw/examples/CMakeFiles/sharing.dir/build
.PHONY : sharing/fast

#=============================================================================
# Target rules for targets named title

# Build rule for target.
title: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 title
.PHONY : title

# fast build rule for target.
title/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/title.dir/build.make external/glfw/tests/CMakeFiles/title.dir/build
.PHONY : title/fast

#=============================================================================
# Target rules for targets named timeout

# Build rule for target.
timeout: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timeout
.PHONY : timeout

# fast build rule for target.
timeout/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/timeout.dir/build.make external/glfw/tests/CMakeFiles/timeout.dir/build
.PHONY : timeout/fast

#=============================================================================
# Target rules for targets named monitors

# Build rule for target.
monitors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monitors
.PHONY : monitors

# fast build rule for target.
monitors/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/monitors.dir/build.make external/glfw/tests/CMakeFiles/monitors.dir/build
.PHONY : monitors/fast

#=============================================================================
# Target rules for targets named clipboard

# Build rule for target.
clipboard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clipboard
.PHONY : clipboard

# fast build rule for target.
clipboard/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/clipboard.dir/build.make external/glfw/tests/CMakeFiles/clipboard.dir/build
.PHONY : clipboard/fast

#=============================================================================
# Target rules for targets named cursor

# Build rule for target.
cursor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cursor
.PHONY : cursor

# fast build rule for target.
cursor/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/cursor.dir/build.make external/glfw/tests/CMakeFiles/cursor.dir/build
.PHONY : cursor/fast

#=============================================================================
# Target rules for targets named msaa

# Build rule for target.
msaa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msaa
.PHONY : msaa

# fast build rule for target.
msaa/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/msaa.dir/build.make external/glfw/tests/CMakeFiles/msaa.dir/build
.PHONY : msaa/fast

#=============================================================================
# Target rules for targets named glfwinfo

# Build rule for target.
glfwinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfwinfo
.PHONY : glfwinfo

# fast build rule for target.
glfwinfo/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/glfwinfo.dir/build.make external/glfw/tests/CMakeFiles/glfwinfo.dir/build
.PHONY : glfwinfo/fast

#=============================================================================
# Target rules for targets named threads

# Build rule for target.
threads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 threads
.PHONY : threads

# fast build rule for target.
threads/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/threads.dir/build.make external/glfw/tests/CMakeFiles/threads.dir/build
.PHONY : threads/fast

#=============================================================================
# Target rules for targets named reopen

# Build rule for target.
reopen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reopen
.PHONY : reopen

# fast build rule for target.
reopen/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/reopen.dir/build.make external/glfw/tests/CMakeFiles/reopen.dir/build
.PHONY : reopen/fast

#=============================================================================
# Target rules for targets named triangle-vulkan

# Build rule for target.
triangle-vulkan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangle-vulkan
.PHONY : triangle-vulkan

# fast build rule for target.
triangle-vulkan/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/triangle-vulkan.dir/build.make external/glfw/tests/CMakeFiles/triangle-vulkan.dir/build
.PHONY : triangle-vulkan/fast

#=============================================================================
# Target rules for targets named opacity

# Build rule for target.
opacity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opacity
.PHONY : opacity

# fast build rule for target.
opacity/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/opacity.dir/build.make external/glfw/tests/CMakeFiles/opacity.dir/build
.PHONY : opacity/fast

#=============================================================================
# Target rules for targets named iconify

# Build rule for target.
iconify: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iconify
.PHONY : iconify

# fast build rule for target.
iconify/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/iconify.dir/build.make external/glfw/tests/CMakeFiles/iconify.dir/build
.PHONY : iconify/fast

#=============================================================================
# Target rules for targets named gamma

# Build rule for target.
gamma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gamma
.PHONY : gamma

# fast build rule for target.
gamma/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/gamma.dir/build.make external/glfw/tests/CMakeFiles/gamma.dir/build
.PHONY : gamma/fast

#=============================================================================
# Target rules for targets named events

# Build rule for target.
events: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 events
.PHONY : events

# fast build rule for target.
events/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/events.dir/build.make external/glfw/tests/CMakeFiles/events.dir/build
.PHONY : events/fast

#=============================================================================
# Target rules for targets named icon

# Build rule for target.
icon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 icon
.PHONY : icon

# fast build rule for target.
icon/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/icon.dir/build.make external/glfw/tests/CMakeFiles/icon.dir/build
.PHONY : icon/fast

#=============================================================================
# Target rules for targets named joysticks

# Build rule for target.
joysticks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 joysticks
.PHONY : joysticks

# fast build rule for target.
joysticks/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/joysticks.dir/build.make external/glfw/tests/CMakeFiles/joysticks.dir/build
.PHONY : joysticks/fast

#=============================================================================
# Target rules for targets named windows

# Build rule for target.
windows: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 windows
.PHONY : windows

# fast build rule for target.
windows/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/windows.dir/build.make external/glfw/tests/CMakeFiles/windows.dir/build
.PHONY : windows/fast

#=============================================================================
# Target rules for targets named empty

# Build rule for target.
empty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 empty
.PHONY : empty

# fast build rule for target.
empty/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/empty.dir/build.make external/glfw/tests/CMakeFiles/empty.dir/build
.PHONY : empty/fast

#=============================================================================
# Target rules for targets named inputlag

# Build rule for target.
inputlag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 inputlag
.PHONY : inputlag

# fast build rule for target.
inputlag/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/inputlag.dir/build.make external/glfw/tests/CMakeFiles/inputlag.dir/build
.PHONY : inputlag/fast

#=============================================================================
# Target rules for targets named tearing

# Build rule for target.
tearing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tearing
.PHONY : tearing

# fast build rule for target.
tearing/fast:
	$(MAKE) -f external/glfw/tests/CMakeFiles/tearing.dir/build.make external/glfw/tests/CMakeFiles/tearing.dir/build
.PHONY : tearing/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f external/glfw/docs/CMakeFiles/docs.dir/build.make external/glfw/docs/CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) -f external/spdlog-1.10.0/CMakeFiles/spdlog.dir/build.make external/spdlog-1.10.0/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

external/glad/src/glad.o: external/glad/src/glad.c.o

.PHONY : external/glad/src/glad.o

# target to build an object file
external/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/glad/src/glad.c.o
.PHONY : external/glad/src/glad.c.o

external/glad/src/glad.i: external/glad/src/glad.c.i

.PHONY : external/glad/src/glad.i

# target to preprocess a source file
external/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/glad/src/glad.c.i
.PHONY : external/glad/src/glad.c.i

external/glad/src/glad.s: external/glad/src/glad.c.s

.PHONY : external/glad/src/glad.s

# target to generate assembly for a file
external/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/glad/src/glad.c.s
.PHONY : external/glad/src/glad.c.s

external/imgui/imgui.o: external/imgui/imgui.cpp.o

.PHONY : external/imgui/imgui.o

# target to build an object file
external/imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.cpp.o

external/imgui/imgui.i: external/imgui/imgui.cpp.i

.PHONY : external/imgui/imgui.i

# target to preprocess a source file
external/imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.cpp.i

external/imgui/imgui.s: external/imgui/imgui.cpp.s

.PHONY : external/imgui/imgui.s

# target to generate assembly for a file
external/imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.cpp.s

external/imgui/imgui_demo.o: external/imgui/imgui_demo.cpp.o

.PHONY : external/imgui/imgui_demo.o

# target to build an object file
external/imgui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_demo.cpp.o
.PHONY : external/imgui/imgui_demo.cpp.o

external/imgui/imgui_demo.i: external/imgui/imgui_demo.cpp.i

.PHONY : external/imgui/imgui_demo.i

# target to preprocess a source file
external/imgui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.cpp.i

external/imgui/imgui_demo.s: external/imgui/imgui_demo.cpp.s

.PHONY : external/imgui/imgui_demo.s

# target to generate assembly for a file
external/imgui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.cpp.s

external/imgui/imgui_draw.o: external/imgui/imgui_draw.cpp.o

.PHONY : external/imgui/imgui_draw.o

# target to build an object file
external/imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.cpp.o

external/imgui/imgui_draw.i: external/imgui/imgui_draw.cpp.i

.PHONY : external/imgui/imgui_draw.i

# target to preprocess a source file
external/imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.cpp.i

external/imgui/imgui_draw.s: external/imgui/imgui_draw.cpp.s

.PHONY : external/imgui/imgui_draw.s

# target to generate assembly for a file
external/imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.cpp.s

external/imgui/imgui_impl_glfw.o: external/imgui/imgui_impl_glfw.cpp.o

.PHONY : external/imgui/imgui_impl_glfw.o

# target to build an object file
external/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_impl_glfw.cpp.o
.PHONY : external/imgui/imgui_impl_glfw.cpp.o

external/imgui/imgui_impl_glfw.i: external/imgui/imgui_impl_glfw.cpp.i

.PHONY : external/imgui/imgui_impl_glfw.i

# target to preprocess a source file
external/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_impl_glfw.cpp.i
.PHONY : external/imgui/imgui_impl_glfw.cpp.i

external/imgui/imgui_impl_glfw.s: external/imgui/imgui_impl_glfw.cpp.s

.PHONY : external/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
external/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_impl_glfw.cpp.s
.PHONY : external/imgui/imgui_impl_glfw.cpp.s

external/imgui/imgui_impl_opengl3.o: external/imgui/imgui_impl_opengl3.cpp.o

.PHONY : external/imgui/imgui_impl_opengl3.o

# target to build an object file
external/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_impl_opengl3.cpp.o
.PHONY : external/imgui/imgui_impl_opengl3.cpp.o

external/imgui/imgui_impl_opengl3.i: external/imgui/imgui_impl_opengl3.cpp.i

.PHONY : external/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
external/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_impl_opengl3.cpp.i
.PHONY : external/imgui/imgui_impl_opengl3.cpp.i

external/imgui/imgui_impl_opengl3.s: external/imgui/imgui_impl_opengl3.cpp.s

.PHONY : external/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
external/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_impl_opengl3.cpp.s
.PHONY : external/imgui/imgui_impl_opengl3.cpp.s

external/imgui/imgui_tables.o: external/imgui/imgui_tables.cpp.o

.PHONY : external/imgui/imgui_tables.o

# target to build an object file
external/imgui/imgui_tables.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.cpp.o

external/imgui/imgui_tables.i: external/imgui/imgui_tables.cpp.i

.PHONY : external/imgui/imgui_tables.i

# target to preprocess a source file
external/imgui/imgui_tables.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.cpp.i

external/imgui/imgui_tables.s: external/imgui/imgui_tables.cpp.s

.PHONY : external/imgui/imgui_tables.s

# target to generate assembly for a file
external/imgui/imgui_tables.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.cpp.s

external/imgui/imgui_widgets.o: external/imgui/imgui_widgets.cpp.o

.PHONY : external/imgui/imgui_widgets.o

# target to build an object file
external/imgui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.cpp.o

external/imgui/imgui_widgets.i: external/imgui/imgui_widgets.cpp.i

.PHONY : external/imgui/imgui_widgets.i

# target to preprocess a source file
external/imgui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.cpp.i

external/imgui/imgui_widgets.s: external/imgui/imgui_widgets.cpp.s

.PHONY : external/imgui/imgui_widgets.s

# target to generate assembly for a file
external/imgui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.cpp.s

src/App.o: src/App.cpp.o

.PHONY : src/App.o

# target to build an object file
src/App.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/App.cpp.o
.PHONY : src/App.cpp.o

src/App.i: src/App.cpp.i

.PHONY : src/App.i

# target to preprocess a source file
src/App.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/App.cpp.i
.PHONY : src/App.cpp.i

src/App.s: src/App.cpp.s

.PHONY : src/App.s

# target to generate assembly for a file
src/App.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/App.cpp.s
.PHONY : src/App.cpp.s

src/audio/audio.o: src/audio/audio.cpp.o

.PHONY : src/audio/audio.o

# target to build an object file
src/audio/audio.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/audio/audio.cpp.o
.PHONY : src/audio/audio.cpp.o

src/audio/audio.i: src/audio/audio.cpp.i

.PHONY : src/audio/audio.i

# target to preprocess a source file
src/audio/audio.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/audio/audio.cpp.i
.PHONY : src/audio/audio.cpp.i

src/audio/audio.s: src/audio/audio.cpp.s

.PHONY : src/audio/audio.s

# target to generate assembly for a file
src/audio/audio.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/audio/audio.cpp.s
.PHONY : src/audio/audio.cpp.s

src/render/Actors/Mesh.o: src/render/Actors/Mesh.cpp.o

.PHONY : src/render/Actors/Mesh.o

# target to build an object file
src/render/Actors/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Actors/Mesh.cpp.o
.PHONY : src/render/Actors/Mesh.cpp.o

src/render/Actors/Mesh.i: src/render/Actors/Mesh.cpp.i

.PHONY : src/render/Actors/Mesh.i

# target to preprocess a source file
src/render/Actors/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Actors/Mesh.cpp.i
.PHONY : src/render/Actors/Mesh.cpp.i

src/render/Actors/Mesh.s: src/render/Actors/Mesh.cpp.s

.PHONY : src/render/Actors/Mesh.s

# target to generate assembly for a file
src/render/Actors/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Actors/Mesh.cpp.s
.PHONY : src/render/Actors/Mesh.cpp.s

src/render/Camera.o: src/render/Camera.cpp.o

.PHONY : src/render/Camera.o

# target to build an object file
src/render/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Camera.cpp.o
.PHONY : src/render/Camera.cpp.o

src/render/Camera.i: src/render/Camera.cpp.i

.PHONY : src/render/Camera.i

# target to preprocess a source file
src/render/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Camera.cpp.i
.PHONY : src/render/Camera.cpp.i

src/render/Camera.s: src/render/Camera.cpp.s

.PHONY : src/render/Camera.s

# target to generate assembly for a file
src/render/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Camera.cpp.s
.PHONY : src/render/Camera.cpp.s

src/render/EBO.o: src/render/EBO.cpp.o

.PHONY : src/render/EBO.o

# target to build an object file
src/render/EBO.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/EBO.cpp.o
.PHONY : src/render/EBO.cpp.o

src/render/EBO.i: src/render/EBO.cpp.i

.PHONY : src/render/EBO.i

# target to preprocess a source file
src/render/EBO.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/EBO.cpp.i
.PHONY : src/render/EBO.cpp.i

src/render/EBO.s: src/render/EBO.cpp.s

.PHONY : src/render/EBO.s

# target to generate assembly for a file
src/render/EBO.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/EBO.cpp.s
.PHONY : src/render/EBO.cpp.s

src/render/GameObject.o: src/render/GameObject.cpp.o

.PHONY : src/render/GameObject.o

# target to build an object file
src/render/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/GameObject.cpp.o
.PHONY : src/render/GameObject.cpp.o

src/render/GameObject.i: src/render/GameObject.cpp.i

.PHONY : src/render/GameObject.i

# target to preprocess a source file
src/render/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/GameObject.cpp.i
.PHONY : src/render/GameObject.cpp.i

src/render/GameObject.s: src/render/GameObject.cpp.s

.PHONY : src/render/GameObject.s

# target to generate assembly for a file
src/render/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/GameObject.cpp.s
.PHONY : src/render/GameObject.cpp.s

src/render/RenderSystem.o: src/render/RenderSystem.cpp.o

.PHONY : src/render/RenderSystem.o

# target to build an object file
src/render/RenderSystem.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/RenderSystem.cpp.o
.PHONY : src/render/RenderSystem.cpp.o

src/render/RenderSystem.i: src/render/RenderSystem.cpp.i

.PHONY : src/render/RenderSystem.i

# target to preprocess a source file
src/render/RenderSystem.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/RenderSystem.cpp.i
.PHONY : src/render/RenderSystem.cpp.i

src/render/RenderSystem.s: src/render/RenderSystem.cpp.s

.PHONY : src/render/RenderSystem.s

# target to generate assembly for a file
src/render/RenderSystem.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/RenderSystem.cpp.s
.PHONY : src/render/RenderSystem.cpp.s

src/render/Shader.o: src/render/Shader.cpp.o

.PHONY : src/render/Shader.o

# target to build an object file
src/render/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Shader.cpp.o
.PHONY : src/render/Shader.cpp.o

src/render/Shader.i: src/render/Shader.cpp.i

.PHONY : src/render/Shader.i

# target to preprocess a source file
src/render/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Shader.cpp.i
.PHONY : src/render/Shader.cpp.i

src/render/Shader.s: src/render/Shader.cpp.s

.PHONY : src/render/Shader.s

# target to generate assembly for a file
src/render/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Shader.cpp.s
.PHONY : src/render/Shader.cpp.s

src/render/Texture.o: src/render/Texture.cpp.o

.PHONY : src/render/Texture.o

# target to build an object file
src/render/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Texture.cpp.o
.PHONY : src/render/Texture.cpp.o

src/render/Texture.i: src/render/Texture.cpp.i

.PHONY : src/render/Texture.i

# target to preprocess a source file
src/render/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Texture.cpp.i
.PHONY : src/render/Texture.cpp.i

src/render/Texture.s: src/render/Texture.cpp.s

.PHONY : src/render/Texture.s

# target to generate assembly for a file
src/render/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/Texture.cpp.s
.PHONY : src/render/Texture.cpp.s

src/render/UI/Objects/UI.o: src/render/UI/Objects/UI.cpp.o

.PHONY : src/render/UI/Objects/UI.o

# target to build an object file
src/render/UI/Objects/UI.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI.cpp.o
.PHONY : src/render/UI/Objects/UI.cpp.o

src/render/UI/Objects/UI.i: src/render/UI/Objects/UI.cpp.i

.PHONY : src/render/UI/Objects/UI.i

# target to preprocess a source file
src/render/UI/Objects/UI.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI.cpp.i
.PHONY : src/render/UI/Objects/UI.cpp.i

src/render/UI/Objects/UI.s: src/render/UI/Objects/UI.cpp.s

.PHONY : src/render/UI/Objects/UI.s

# target to generate assembly for a file
src/render/UI/Objects/UI.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI.cpp.s
.PHONY : src/render/UI/Objects/UI.cpp.s

src/render/UI/Objects/UI_Button.o: src/render/UI/Objects/UI_Button.cpp.o

.PHONY : src/render/UI/Objects/UI_Button.o

# target to build an object file
src/render/UI/Objects/UI_Button.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI_Button.cpp.o
.PHONY : src/render/UI/Objects/UI_Button.cpp.o

src/render/UI/Objects/UI_Button.i: src/render/UI/Objects/UI_Button.cpp.i

.PHONY : src/render/UI/Objects/UI_Button.i

# target to preprocess a source file
src/render/UI/Objects/UI_Button.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI_Button.cpp.i
.PHONY : src/render/UI/Objects/UI_Button.cpp.i

src/render/UI/Objects/UI_Button.s: src/render/UI/Objects/UI_Button.cpp.s

.PHONY : src/render/UI/Objects/UI_Button.s

# target to generate assembly for a file
src/render/UI/Objects/UI_Button.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI_Button.cpp.s
.PHONY : src/render/UI/Objects/UI_Button.cpp.s

src/render/UI/Objects/UI_Image.o: src/render/UI/Objects/UI_Image.cpp.o

.PHONY : src/render/UI/Objects/UI_Image.o

# target to build an object file
src/render/UI/Objects/UI_Image.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI_Image.cpp.o
.PHONY : src/render/UI/Objects/UI_Image.cpp.o

src/render/UI/Objects/UI_Image.i: src/render/UI/Objects/UI_Image.cpp.i

.PHONY : src/render/UI/Objects/UI_Image.i

# target to preprocess a source file
src/render/UI/Objects/UI_Image.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI_Image.cpp.i
.PHONY : src/render/UI/Objects/UI_Image.cpp.i

src/render/UI/Objects/UI_Image.s: src/render/UI/Objects/UI_Image.cpp.s

.PHONY : src/render/UI/Objects/UI_Image.s

# target to generate assembly for a file
src/render/UI/Objects/UI_Image.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI_Image.cpp.s
.PHONY : src/render/UI/Objects/UI_Image.cpp.s

src/render/UI/Objects/UI_Text.o: src/render/UI/Objects/UI_Text.cpp.o

.PHONY : src/render/UI/Objects/UI_Text.o

# target to build an object file
src/render/UI/Objects/UI_Text.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI_Text.cpp.o
.PHONY : src/render/UI/Objects/UI_Text.cpp.o

src/render/UI/Objects/UI_Text.i: src/render/UI/Objects/UI_Text.cpp.i

.PHONY : src/render/UI/Objects/UI_Text.i

# target to preprocess a source file
src/render/UI/Objects/UI_Text.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI_Text.cpp.i
.PHONY : src/render/UI/Objects/UI_Text.cpp.i

src/render/UI/Objects/UI_Text.s: src/render/UI/Objects/UI_Text.cpp.s

.PHONY : src/render/UI/Objects/UI_Text.s

# target to generate assembly for a file
src/render/UI/Objects/UI_Text.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/Objects/UI_Text.cpp.s
.PHONY : src/render/UI/Objects/UI_Text.cpp.s

src/render/UI/UI_manager.o: src/render/UI/UI_manager.cpp.o

.PHONY : src/render/UI/UI_manager.o

# target to build an object file
src/render/UI/UI_manager.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/UI_manager.cpp.o
.PHONY : src/render/UI/UI_manager.cpp.o

src/render/UI/UI_manager.i: src/render/UI/UI_manager.cpp.i

.PHONY : src/render/UI/UI_manager.i

# target to preprocess a source file
src/render/UI/UI_manager.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/UI_manager.cpp.i
.PHONY : src/render/UI/UI_manager.cpp.i

src/render/UI/UI_manager.s: src/render/UI/UI_manager.cpp.s

.PHONY : src/render/UI/UI_manager.s

# target to generate assembly for a file
src/render/UI/UI_manager.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/UI/UI_manager.cpp.s
.PHONY : src/render/UI/UI_manager.cpp.s

src/render/VAO.o: src/render/VAO.cpp.o

.PHONY : src/render/VAO.o

# target to build an object file
src/render/VAO.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/VAO.cpp.o
.PHONY : src/render/VAO.cpp.o

src/render/VAO.i: src/render/VAO.cpp.i

.PHONY : src/render/VAO.i

# target to preprocess a source file
src/render/VAO.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/VAO.cpp.i
.PHONY : src/render/VAO.cpp.i

src/render/VAO.s: src/render/VAO.cpp.s

.PHONY : src/render/VAO.s

# target to generate assembly for a file
src/render/VAO.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/VAO.cpp.s
.PHONY : src/render/VAO.cpp.s

src/render/VBO.o: src/render/VBO.cpp.o

.PHONY : src/render/VBO.o

# target to build an object file
src/render/VBO.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/VBO.cpp.o
.PHONY : src/render/VBO.cpp.o

src/render/VBO.i: src/render/VBO.cpp.i

.PHONY : src/render/VBO.i

# target to preprocess a source file
src/render/VBO.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/VBO.cpp.i
.PHONY : src/render/VBO.cpp.i

src/render/VBO.s: src/render/VBO.cpp.s

.PHONY : src/render/VBO.s

# target to generate assembly for a file
src/render/VBO.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/render/VBO.cpp.s
.PHONY : src/render/VBO.cpp.s

src/utils/loader/ResourceLoader.o: src/utils/loader/ResourceLoader.cpp.o

.PHONY : src/utils/loader/ResourceLoader.o

# target to build an object file
src/utils/loader/ResourceLoader.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/loader/ResourceLoader.cpp.o
.PHONY : src/utils/loader/ResourceLoader.cpp.o

src/utils/loader/ResourceLoader.i: src/utils/loader/ResourceLoader.cpp.i

.PHONY : src/utils/loader/ResourceLoader.i

# target to preprocess a source file
src/utils/loader/ResourceLoader.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/loader/ResourceLoader.cpp.i
.PHONY : src/utils/loader/ResourceLoader.cpp.i

src/utils/loader/ResourceLoader.s: src/utils/loader/ResourceLoader.cpp.s

.PHONY : src/utils/loader/ResourceLoader.s

# target to generate assembly for a file
src/utils/loader/ResourceLoader.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/loader/ResourceLoader.cpp.s
.PHONY : src/utils/loader/ResourceLoader.cpp.s

src/utils/log.o: src/utils/log.cpp.o

.PHONY : src/utils/log.o

# target to build an object file
src/utils/log.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/log.cpp.o
.PHONY : src/utils/log.cpp.o

src/utils/log.i: src/utils/log.cpp.i

.PHONY : src/utils/log.i

# target to preprocess a source file
src/utils/log.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/log.cpp.i
.PHONY : src/utils/log.cpp.i

src/utils/log.s: src/utils/log.cpp.s

.PHONY : src/utils/log.s

# target to generate assembly for a file
src/utils/log.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/log.cpp.s
.PHONY : src/utils/log.cpp.s

src/utils/native/FileDialog.o: src/utils/native/FileDialog.cpp.o

.PHONY : src/utils/native/FileDialog.o

# target to build an object file
src/utils/native/FileDialog.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/native/FileDialog.cpp.o
.PHONY : src/utils/native/FileDialog.cpp.o

src/utils/native/FileDialog.i: src/utils/native/FileDialog.cpp.i

.PHONY : src/utils/native/FileDialog.i

# target to preprocess a source file
src/utils/native/FileDialog.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/native/FileDialog.cpp.i
.PHONY : src/utils/native/FileDialog.cpp.i

src/utils/native/FileDialog.s: src/utils/native/FileDialog.cpp.s

.PHONY : src/utils/native/FileDialog.s

# target to generate assembly for a file
src/utils/native/FileDialog.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/native/FileDialog.cpp.s
.PHONY : src/utils/native/FileDialog.cpp.s

src/utils/native/FolderDialog.o: src/utils/native/FolderDialog.cpp.o

.PHONY : src/utils/native/FolderDialog.o

# target to build an object file
src/utils/native/FolderDialog.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/native/FolderDialog.cpp.o
.PHONY : src/utils/native/FolderDialog.cpp.o

src/utils/native/FolderDialog.i: src/utils/native/FolderDialog.cpp.i

.PHONY : src/utils/native/FolderDialog.i

# target to preprocess a source file
src/utils/native/FolderDialog.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/native/FolderDialog.cpp.i
.PHONY : src/utils/native/FolderDialog.cpp.i

src/utils/native/FolderDialog.s: src/utils/native/FolderDialog.cpp.s

.PHONY : src/utils/native/FolderDialog.s

# target to generate assembly for a file
src/utils/native/FolderDialog.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/utils/native/FolderDialog.cpp.s
.PHONY : src/utils/native/FolderDialog.cpp.s

src/window/events/EventSystem.o: src/window/events/EventSystem.cpp.o

.PHONY : src/window/events/EventSystem.o

# target to build an object file
src/window/events/EventSystem.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/EventSystem.cpp.o
.PHONY : src/window/events/EventSystem.cpp.o

src/window/events/EventSystem.i: src/window/events/EventSystem.cpp.i

.PHONY : src/window/events/EventSystem.i

# target to preprocess a source file
src/window/events/EventSystem.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/EventSystem.cpp.i
.PHONY : src/window/events/EventSystem.cpp.i

src/window/events/EventSystem.s: src/window/events/EventSystem.cpp.s

.PHONY : src/window/events/EventSystem.s

# target to generate assembly for a file
src/window/events/EventSystem.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/EventSystem.cpp.s
.PHONY : src/window/events/EventSystem.cpp.s

src/window/events/keyboard/GetKey.o: src/window/events/keyboard/GetKey.cpp.o

.PHONY : src/window/events/keyboard/GetKey.o

# target to build an object file
src/window/events/keyboard/GetKey.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/keyboard/GetKey.cpp.o
.PHONY : src/window/events/keyboard/GetKey.cpp.o

src/window/events/keyboard/GetKey.i: src/window/events/keyboard/GetKey.cpp.i

.PHONY : src/window/events/keyboard/GetKey.i

# target to preprocess a source file
src/window/events/keyboard/GetKey.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/keyboard/GetKey.cpp.i
.PHONY : src/window/events/keyboard/GetKey.cpp.i

src/window/events/keyboard/GetKey.s: src/window/events/keyboard/GetKey.cpp.s

.PHONY : src/window/events/keyboard/GetKey.s

# target to generate assembly for a file
src/window/events/keyboard/GetKey.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/keyboard/GetKey.cpp.s
.PHONY : src/window/events/keyboard/GetKey.cpp.s

src/window/events/keyboard/keyboardEvent.o: src/window/events/keyboard/keyboardEvent.cpp.o

.PHONY : src/window/events/keyboard/keyboardEvent.o

# target to build an object file
src/window/events/keyboard/keyboardEvent.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/keyboard/keyboardEvent.cpp.o
.PHONY : src/window/events/keyboard/keyboardEvent.cpp.o

src/window/events/keyboard/keyboardEvent.i: src/window/events/keyboard/keyboardEvent.cpp.i

.PHONY : src/window/events/keyboard/keyboardEvent.i

# target to preprocess a source file
src/window/events/keyboard/keyboardEvent.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/keyboard/keyboardEvent.cpp.i
.PHONY : src/window/events/keyboard/keyboardEvent.cpp.i

src/window/events/keyboard/keyboardEvent.s: src/window/events/keyboard/keyboardEvent.cpp.s

.PHONY : src/window/events/keyboard/keyboardEvent.s

# target to generate assembly for a file
src/window/events/keyboard/keyboardEvent.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/keyboard/keyboardEvent.cpp.s
.PHONY : src/window/events/keyboard/keyboardEvent.cpp.s

src/window/events/mouse/mouseEvent.o: src/window/events/mouse/mouseEvent.cpp.o

.PHONY : src/window/events/mouse/mouseEvent.o

# target to build an object file
src/window/events/mouse/mouseEvent.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/mouse/mouseEvent.cpp.o
.PHONY : src/window/events/mouse/mouseEvent.cpp.o

src/window/events/mouse/mouseEvent.i: src/window/events/mouse/mouseEvent.cpp.i

.PHONY : src/window/events/mouse/mouseEvent.i

# target to preprocess a source file
src/window/events/mouse/mouseEvent.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/mouse/mouseEvent.cpp.i
.PHONY : src/window/events/mouse/mouseEvent.cpp.i

src/window/events/mouse/mouseEvent.s: src/window/events/mouse/mouseEvent.cpp.s

.PHONY : src/window/events/mouse/mouseEvent.s

# target to generate assembly for a file
src/window/events/mouse/mouseEvent.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/mouse/mouseEvent.cpp.s
.PHONY : src/window/events/mouse/mouseEvent.cpp.s

src/window/events/windowEvent.o: src/window/events/windowEvent.cpp.o

.PHONY : src/window/events/windowEvent.o

# target to build an object file
src/window/events/windowEvent.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/windowEvent.cpp.o
.PHONY : src/window/events/windowEvent.cpp.o

src/window/events/windowEvent.i: src/window/events/windowEvent.cpp.i

.PHONY : src/window/events/windowEvent.i

# target to preprocess a source file
src/window/events/windowEvent.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/windowEvent.cpp.i
.PHONY : src/window/events/windowEvent.cpp.i

src/window/events/windowEvent.s: src/window/events/windowEvent.cpp.s

.PHONY : src/window/events/windowEvent.s

# target to generate assembly for a file
src/window/events/windowEvent.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/events/windowEvent.cpp.s
.PHONY : src/window/events/windowEvent.cpp.s

src/window/window.o: src/window/window.cpp.o

.PHONY : src/window/window.o

# target to build an object file
src/window/window.cpp.o:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/window.cpp.o
.PHONY : src/window/window.cpp.o

src/window/window.i: src/window/window.cpp.i

.PHONY : src/window/window.i

# target to preprocess a source file
src/window/window.cpp.i:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/window.cpp.i
.PHONY : src/window/window.cpp.i

src/window/window.s: src/window/window.cpp.s

.PHONY : src/window/window.s

# target to generate assembly for a file
src/window/window.cpp.s:
	$(MAKE) -f CMakeFiles/MidnightEngine.dir/build.make CMakeFiles/MidnightEngine.dir/src/window/window.cpp.s
.PHONY : src/window/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... MidnightEngine"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... update_mappings"
	@echo "... wave"
	@echo "... simple"
	@echo "... gears"
	@echo "... boing"
	@echo "... heightmap"
	@echo "... splitview"
	@echo "... offscreen"
	@echo "... particles"
	@echo "... sharing"
	@echo "... title"
	@echo "... timeout"
	@echo "... monitors"
	@echo "... clipboard"
	@echo "... cursor"
	@echo "... msaa"
	@echo "... glfwinfo"
	@echo "... threads"
	@echo "... reopen"
	@echo "... triangle-vulkan"
	@echo "... opacity"
	@echo "... iconify"
	@echo "... gamma"
	@echo "... events"
	@echo "... icon"
	@echo "... joysticks"
	@echo "... windows"
	@echo "... empty"
	@echo "... inputlag"
	@echo "... tearing"
	@echo "... docs"
	@echo "... spdlog"
	@echo "... external/glad/src/glad.o"
	@echo "... external/glad/src/glad.i"
	@echo "... external/glad/src/glad.s"
	@echo "... external/imgui/imgui.o"
	@echo "... external/imgui/imgui.i"
	@echo "... external/imgui/imgui.s"
	@echo "... external/imgui/imgui_demo.o"
	@echo "... external/imgui/imgui_demo.i"
	@echo "... external/imgui/imgui_demo.s"
	@echo "... external/imgui/imgui_draw.o"
	@echo "... external/imgui/imgui_draw.i"
	@echo "... external/imgui/imgui_draw.s"
	@echo "... external/imgui/imgui_impl_glfw.o"
	@echo "... external/imgui/imgui_impl_glfw.i"
	@echo "... external/imgui/imgui_impl_glfw.s"
	@echo "... external/imgui/imgui_impl_opengl3.o"
	@echo "... external/imgui/imgui_impl_opengl3.i"
	@echo "... external/imgui/imgui_impl_opengl3.s"
	@echo "... external/imgui/imgui_tables.o"
	@echo "... external/imgui/imgui_tables.i"
	@echo "... external/imgui/imgui_tables.s"
	@echo "... external/imgui/imgui_widgets.o"
	@echo "... external/imgui/imgui_widgets.i"
	@echo "... external/imgui/imgui_widgets.s"
	@echo "... src/App.o"
	@echo "... src/App.i"
	@echo "... src/App.s"
	@echo "... src/audio/audio.o"
	@echo "... src/audio/audio.i"
	@echo "... src/audio/audio.s"
	@echo "... src/render/Actors/Mesh.o"
	@echo "... src/render/Actors/Mesh.i"
	@echo "... src/render/Actors/Mesh.s"
	@echo "... src/render/Camera.o"
	@echo "... src/render/Camera.i"
	@echo "... src/render/Camera.s"
	@echo "... src/render/EBO.o"
	@echo "... src/render/EBO.i"
	@echo "... src/render/EBO.s"
	@echo "... src/render/GameObject.o"
	@echo "... src/render/GameObject.i"
	@echo "... src/render/GameObject.s"
	@echo "... src/render/RenderSystem.o"
	@echo "... src/render/RenderSystem.i"
	@echo "... src/render/RenderSystem.s"
	@echo "... src/render/Shader.o"
	@echo "... src/render/Shader.i"
	@echo "... src/render/Shader.s"
	@echo "... src/render/Texture.o"
	@echo "... src/render/Texture.i"
	@echo "... src/render/Texture.s"
	@echo "... src/render/UI/Objects/UI.o"
	@echo "... src/render/UI/Objects/UI.i"
	@echo "... src/render/UI/Objects/UI.s"
	@echo "... src/render/UI/Objects/UI_Button.o"
	@echo "... src/render/UI/Objects/UI_Button.i"
	@echo "... src/render/UI/Objects/UI_Button.s"
	@echo "... src/render/UI/Objects/UI_Image.o"
	@echo "... src/render/UI/Objects/UI_Image.i"
	@echo "... src/render/UI/Objects/UI_Image.s"
	@echo "... src/render/UI/Objects/UI_Text.o"
	@echo "... src/render/UI/Objects/UI_Text.i"
	@echo "... src/render/UI/Objects/UI_Text.s"
	@echo "... src/render/UI/UI_manager.o"
	@echo "... src/render/UI/UI_manager.i"
	@echo "... src/render/UI/UI_manager.s"
	@echo "... src/render/VAO.o"
	@echo "... src/render/VAO.i"
	@echo "... src/render/VAO.s"
	@echo "... src/render/VBO.o"
	@echo "... src/render/VBO.i"
	@echo "... src/render/VBO.s"
	@echo "... src/utils/loader/ResourceLoader.o"
	@echo "... src/utils/loader/ResourceLoader.i"
	@echo "... src/utils/loader/ResourceLoader.s"
	@echo "... src/utils/log.o"
	@echo "... src/utils/log.i"
	@echo "... src/utils/log.s"
	@echo "... src/utils/native/FileDialog.o"
	@echo "... src/utils/native/FileDialog.i"
	@echo "... src/utils/native/FileDialog.s"
	@echo "... src/utils/native/FolderDialog.o"
	@echo "... src/utils/native/FolderDialog.i"
	@echo "... src/utils/native/FolderDialog.s"
	@echo "... src/window/events/EventSystem.o"
	@echo "... src/window/events/EventSystem.i"
	@echo "... src/window/events/EventSystem.s"
	@echo "... src/window/events/keyboard/GetKey.o"
	@echo "... src/window/events/keyboard/GetKey.i"
	@echo "... src/window/events/keyboard/GetKey.s"
	@echo "... src/window/events/keyboard/keyboardEvent.o"
	@echo "... src/window/events/keyboard/keyboardEvent.i"
	@echo "... src/window/events/keyboard/keyboardEvent.s"
	@echo "... src/window/events/mouse/mouseEvent.o"
	@echo "... src/window/events/mouse/mouseEvent.i"
	@echo "... src/window/events/mouse/mouseEvent.s"
	@echo "... src/window/events/windowEvent.o"
	@echo "... src/window/events/windowEvent.i"
	@echo "... src/window/events/windowEvent.s"
	@echo "... src/window/window.o"
	@echo "... src/window/window.i"
	@echo "... src/window/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

